server:
  port : 8083

#microservices configuration
spring:
  application:
    name: fl-project-service
  #database configuration:mysql
  datasource:
    url: jdbc:mysql://mysqlffdb.chevdymucho3.eu-west-1.rds.amazonaws.com/fl_projects?useSSL=false
    username: bheem
    password: VNSGUfreelance

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/

db:
  queries:
    projects:
      insertProject: insert into projects(ClientId,ProjectName,ProjectDescription,IsConfidential,BidStartDate,BidEndDate,MinPrice,MaxPrice) values(?,?,?,?,?,?,?,?)
      selectAllProject: select * from projects WHERE Status IN ('POSTED','BID_IN_PROGRESS','BID_COMPLETE')
      selectProjectByProjectId: select * from projects where ProjectId = ?
      selectProjectByProjectIds: select * from projects where Status IN ('POSTED','BID_IN_PROGRESS','BID_COMPLETE') AND ProjectId in (%s)
      selectAssignedProjectsByProjectIds : select * from projects where ProjectId IN (:projectIds) and status IN (:status)
      updateProjectByProjectId: update projects set ProjectName=?,ProjectDescription=?,MinPrice=?,MaxPrice=? where ProjectId=?
      updateProjectStatus: update projects set Status = ? WHERE ProjectId = ?
      deleteProjectByProjectId: delete from projects where ProjectId=?
      selectProjectsByClientIdAndStatus : select * from projects WHERE ClientId = :clientId AND  Status IN (:status)
      selectAllStatusProjects: select * from projects
    paymentType:
      insertPaymentType: insert into paymentType(paymentType)values(?)
      selectAllPaymentType: select * from paymentType
    rating:
      insertRating: insert into ratings (userId,projectId,ratingDescription,Rating) values (?,?,?,?)
      selectAllRating: select * from ratings
      selectRatingByRatingId: select * from ratings where ratingId = ?
      selectRatingByUserId: select * from ratings where userId = ?
      selectRatingByProjectId: select * from ratings where projectId = ?
      updateRatingByRatingId: update ratings set ratingDescription = ?,Rating =? where ratingId =?
      removeRatingByRatingId: delete from ratings where ratingId =?
    projectAssignment:
      assignBid: insert into projectAssignment (bidId) values (?)


service:
  props:
    webServices:
      fl-skill-service:
        endpoint: http://localhost:8082/fls/project-skills
      fl-bid-service:
        endpoint: http://localhost:8084/flb/bids