server:
  port : 8082

#microservices configuration
spring:
  application:
    name: fl-skill-service
  #database configuration:mysql
  datasource:
    url: jdbc:mysql://mysqlffdb.chevdymucho3.eu-west-1.rds.amazonaws.com/fl_skills?useSSL=false
    username: bheem
    password: VNSGUfreelance

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/

db:
  queries:
    categories:
      insertCategory: INSERT INTO categories (CategoryName) values (?)
      selectAllCategorySkills: SELECT c.CategoryId, c.CategoryName,c.LogoUrl, s.SkillId, s.SkillName,s.CategoryId,s.CreatedDate,s.isDeleted FROM categories c INNER JOIN skills s
                               ON c.CategoryId=s.CategoryId and c.IsDeleted=0 and s.IsDeleted=0 ORDER BY c.CategoryName,s.SkillName ;
      selectCategorySkillsByCategoryId: SELECT c.CategoryId, c.CategoryName,c.LogoUrl, s.SkillId, s.SkillName,s.CategoryId, s.CreatedDate,s.isDeleted FROM categories c INNER JOIN skills s
                                        ON c.CategoryId=s.CategoryId and c.IsDeleted=0 and s.IsDeleted=0 and c.CategoryId=? ORDER BY c.CategoryId ;
      updateCategory: UPDATE categories set CategoryName = ? WHERE CategoryId = ? and IsDeleted=0
      updateCategoryLogo: UPDATE categories set LogoURL = ? WHERE CategoryId = ? and IsDeleted=0
      removeCategory: UPDATE categories set isDeleted = 1 WHERE CategoryId = ?

    skills:
      insertSkill: INSERT INTO skills(SkillName,CategoryId) values(?,?)
      selectAllSkills: SELECT * from skills WHERE IsDeleted=0 ORDER BY SkillName
      selectSkillBySkillId: SELECT * from skills WHERE IsDeleted=0 and SkillId = ?
      selectSkillByCategoryId: SELECT * from skills WHERE IsDeleted=0 and CategoryId=?
      updateSkill: UPDATE skills set SkillName = ?, CategoryId=? WHERE SkillId= ? and IsDeleted=0
      removeSkill: UPDATE skills set isDeleted = 1 WHERE skillId = ?

    projectSkills:
      insertProjectSkill: INSERT INTO projectskills (ProjectId,SkillId) values(?,?)
      selectProjectSkillDetails: SELECT  ps.ProjectId, s.SkillId, s.SkillName, s.CategoryId from projectskills ps INNER JOIN
                                 skills s on ps.SkillId=s.SkillId
      selectProjectSkillDetailsByProjectId: SELECT  ps.ProjectId, s.SkillId, s.SkillName, s.CategoryId from projectskills ps INNER JOIN 
                                            skills s on ps.SkillId=s.SkillId and ProjectId=?
      selectProjectSkillDetailsBySkillId: SELECT  ps.ProjectId, s.SkillId, s.SkillName, s.CategoryId from projectskills ps INNER JOIN
        skills s on ps.SkillId=s.SkillId where ps.SkillId IN (:skillId)
      selectProjectSkillDetailsByCategoryId: SELECT  ps.ProjectId, s.SkillId, s.SkillName, s.CategoryId from projectskills ps INNER JOIN
        skills s on ps.SkillId=s.SkillId inner JOIN categories c on s.CategoryId = c.CategoryId where c.CategoryId=?

    userSkills:
      insertUserSkill: INSERT INTO userskills (UserId,SkillId) values(?,?)
      selectUserSkillDetails: SELECT us.UserId,s.SkillId,s.SkillName,s.categoryId from userskills us INNER JOIN 
                    skills s on us.SkillId = s.SkillId
      selectUserSkillsByUserId: SELECT us.UserId,s.SkillId,s.SkillName,s.categoryId from userskills us INNER JOIN
                                      skills s on us.SkillId = s.SkillId and UserId=?
      selectUserSkillsInSkillIds: SELECT  us.UserId,s.SkillId,s.SkillName,s.CategoryId from skills s INNER JOIN userskills us on us.SkillId = s.SkillId and us.UserId in
          (SELECT DISTINCT us.UserId from skills s INNER JOIN userskills us on us.SkillId = s.SkillId and s.SkillId IN (:skillIds))
      selectUserSkillsByCategoryId: SELECT us.UserId, s.SkillId, s.SkillName, s.CategoryId
          FROM skills s
          INNER JOIN userskills us ON us.SkillId = s.SkillId
          AND us.UserId IN (
          SELECT DISTINCT us.UserId
          FROM skills s
          INNER JOIN userskills us ON us.SkillId = s.SkillId
          INNER JOIN categories c ON c.CategoryId = s.CategoryId
          AND c.CategoryId = ?)
          ORDER BY us.UserId
