export enum ProjectStatus {
  POSTED = 'POSTED',
  BID_IN_PROGRESS = 'BID_IN_PROGRESS',
  BID_COMPLETE = 'BID_COMPLETE',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  INACTIVE = 'INACTIVE',
}
